import { NextResponse } from 'next/server';
import { authenticatedFetch } from '@/lib/api-client';
import { API_BASE_URL } from '@/config/constants';

/**
 * Change Order Agreement — BFF proxy to the NestJS portal service.
 *
 * The real draft is generated by `POST /api/v1/portal/contracts/generate`
 * (JWT-guarded) and is explicitly labeled a draft. No Odoo sales-order
 * creation is claimed here: the backend never creates or claims to create an
 * Odoo quotation, and this route never fabricates integration status.
 */
export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { title, impactAmount, description } = body as {
      title?: string;
      impactAmount?: string;
      description?: string;
    };

    if (!title || !description) {
      return NextResponse.json(
        { error: 'Title and description required' },
        { status: 400 },
      );
    }

    const response = await authenticatedFetch(
      `${API_BASE_URL}/api/v1/portal/contracts/generate`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title,
          impactAmount: impactAmount ?? '',
          description,
        }),
        signal: AbortSignal.timeout(15000),
      },
    );

    if (response.ok) {
      const data: unknown = await response.json();
      return NextResponse.json(data);
    }

    if (response.status === 401 || response.status === 403) {
      return NextResponse.json(
        { error: 'Unauthorized — sign in to the client portal to generate contracts' },
        { status: 401 },
      );
    }

    return NextResponse.json(
      { error: 'Contract generation failed on the backend' },
      { status: 502 },
    );
  } catch {
    return NextResponse.json(
      {
        error:
          'Contract generation is temporarily unavailable — service pending. No document was created.',
      },
      { status: 503 },
    );
  }
}
