import { NextRequest, NextResponse } from 'next/server';
import { proxyToBackend } from '@/lib/bff';

/**
 * Change Order Agreement — BFF proxy to the NestJS portal service.
 *
 * The real draft is generated by `POST /api/v1/portal/contracts/generate`
 * (JWT-guarded) and is explicitly labeled a draft. No Odoo sales-order
 * creation is claimed here: the backend never creates or claims to create an
 * Odoo quotation, and this route never fabricates integration status.
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { title, impactAmount, description } = body as {
      title?: string;
      impactAmount?: string;
      description?: string;
    };

    if (!title || !description) {
      return NextResponse.json(
        { error: 'Title and description required' },
        { status: 400 },
      );
    }

    return proxyToBackend('/api/v1/portal/contracts/generate', request, {
      method: 'POST',
      body: {
        title,
        impactAmount: impactAmount ?? '',
        description,
      },
    });
  } catch {
    return NextResponse.json(
      {
        error:
          'Contract generation is temporarily unavailable — service pending. No document was created.',
      },
      { status: 503 },
    );
  }
}
