import { NextRequest, NextResponse } from 'next/server';
import { proxyToBackend } from '@/lib/bff';

/**
 * Executive Project Brief — BFF proxy to the NestJS portal service.
 *
 * The real report is generated by `GET /api/v1/portal/reports/executive-brief`
 * (JWT-guarded) from live Odoo accounting + project data. Auth credentials
 * (auth_token cookie first, Bearer header fallback) are forwarded upstream by
 * `proxyToBackend` — the browser-only module token in `lib/api-client.ts` is
 * null in server contexts and must not be used here. This route never
 * fabricates figures: upstream 401/403/404/5xx pass through honestly and an
 * unreachable backend yields 502.
 */
export async function GET(request: NextRequest) {
  const projectId = request.nextUrl.searchParams.get('projectId');

  if (!projectId) {
    return NextResponse.json(
      { error: 'projectId query parameter is required' },
      { status: 400 },
    );
  }

  return proxyToBackend(
    `/api/v1/portal/reports/executive-brief?projectId=${encodeURIComponent(projectId)}`,
    request,
    { method: 'GET', timeoutMs: 15_000 },
  );
}