import { NextResponse } from 'next/server';
import { authenticatedFetch } from '@/lib/api-client';
import { API_BASE_URL } from '@/config/constants';

/**
 * Executive Project Brief — BFF proxy to the NestJS portal service.
 *
 * The real report is generated by `GET /api/v1/portal/reports/executive-brief`
 * (JWT-guarded) from live Odoo accounting + project data. This route never
 * fabricates figures: any backend failure returns an honest error.
 */
export async function GET(request: Request) {
  const projectId = new URL(request.url).searchParams.get('projectId');

  if (!projectId) {
    return NextResponse.json(
      { error: 'projectId query parameter is required' },
      { status: 400 },
    );
  }

  try {
    const response = await authenticatedFetch(
      `${API_BASE_URL}/api/v1/portal/reports/executive-brief?projectId=${encodeURIComponent(projectId)}`,
      {
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
        signal: AbortSignal.timeout(15000),
      },
    );

    if (response.ok) {
      const data: unknown = await response.json();
      return NextResponse.json(data);
    }

    if (response.status === 401 || response.status === 403) {
      return NextResponse.json(
        { error: 'Unauthorized — sign in to the client portal to access executive briefs' },
        { status: 401 },
      );
    }

    if (response.status === 404) {
      return NextResponse.json(
        { error: 'Project not found for the authenticated client' },
        { status: 404 },
      );
    }

    return NextResponse.json(
      { error: 'Executive brief generation failed on the backend' },
      { status: 502 },
    );
  } catch {
    return NextResponse.json(
      {
        error:
          'Executive brief report generation is temporarily unavailable — data integration pending. Please try again later.',
      },
      { status: 503 },
    );
  }
}
