// lucide-react type declarations
// The lucide-react package (v1.28.0) has a broken types reference in its package.json
// (points to dist/lucide-react.d.ts which doesn't exist).
// This declaration file provides the minimal types needed by the app.

declare module 'lucide-react' {
  import * as React from 'react';

  interface LucideProps extends React.SVGAttributes<SVGElement> {
    size?: number | string;
    color?: string;
    strokeWidth?: number;
    strokeLinecap?: 'round' | 'square' | 'butt';
    strokeLinejoin?: 'round' | 'miter' | 'bevel';
    fill?: string;
    absoluteStrokeWidth?: boolean;
    Vue?: boolean;
  }

  // Core icons used in the app
  export function X(props?: LucideProps): React.ReactElement;
  export function Check(props?: LucideProps): React.ReactElement;
  export function ChevronDown(props?: LucideProps): React.ReactElement;
  export function ChevronUp(props?: LucideProps): React.ReactElement;
  export function Loader(props?: LucideProps): React.ReactElement;
  export function Sparkles(props?: LucideProps): React.ReactElement;
  export function TrendingUp(props?: LucideProps): React.ReactElement;
  export function Search(props?: LucideProps): React.ReactElement;
  export function Bell(props?: LucideProps): React.ReactElement;
  export function Menu(props?: LucideProps): React.ReactElement;
  export function Sun(props?: LucideProps): React.ReactElement;
  export function Moon(props?: LucideProps): React.ReactElement;
  export function Settings(props?: LucideProps): React.ReactElement;
  export function LogOut(props?: LucideProps): React.ReactElement;
  export function User(props?: LucideProps): React.ReactElement;
  export function Mail(props?: LucideProps): React.ReactElement;
  export function Phone(props?: LucideProps): React.ReactElement;
  export function MapPin(props?: LucideProps): React.ReactElement;
  export function Clock(props?: LucideProps): React.ReactElement;
  export function Calendar(props?: LucideProps): React.ReactElement;
  export function FileText(props?: LucideProps): React.ReactElement;
  export function Image(props?: LucideProps): React.ReactElement;
  export function Video(props?: LucideProps): React.ReactElement;
  export function Music(props?: LucideProps): React.ReactElement;
  export function Code(props?: LucideProps): React.ReactElement;
  export function Palette(props?: LucideProps): React.ReactElement;
  export function Brush(props?: LucideProps): React.ReactElement;
  export function PenLine(props?: LucideProps): React.ReactElement;
  export function CircleDot(props?: LucideProps): React.ReactElement;
  export function Eye(props?: LucideProps): React.ReactElement;
  export function EyeOff(props?: LucideProps): React.ReactElement;
  export function Lock(props?: LucideProps): React.ReactElement;
  export function Unlock(props?: LucideProps): React.ReactElement;
  export function Shield(props?: LucideProps): React.ReactElement;
  export function ShieldAlert(props?: LucideProps): React.ReactElement;
  export function AlertCircle(props?: LucideProps): React.ReactElement;
  export function Info(props?: LucideProps): React.ReactElement;
  export function HelpCircle(props?: LucideProps): React.ReactElement;
  export function MessageSquare(props?: LucideProps): React.ReactElement;
  export function Send(props?: LucideProps): React.ReactElement;
  export function Heart(props?: LucideProps): React.ReactElement;
  export function Star(props?: LucideProps): React.ReactElement;
  export function ThumbsUp(props?: LucideProps): React.ReactElement;
  export function ThumbsDown(props?: LucideProps): React.ReactElement;
  export function Bookmark(props?: LucideProps): React.ReactElement;
  export function Share2(props?: LucideProps): React.ReactElement;
  export function ExternalLink(props?: LucideProps): React.ReactElement;
  export function ArrowLeft(props?: LucideProps): React.ReactElement;
  export function ArrowRight(props?: LucideProps): React.ReactElement;
  export function ArrowUp(props?: LucideProps): React.ReactElement;
  export function ArrowDown(props?: LucideProps): React.ReactElement;
  export function ChevronLeft(props?: LucideProps): React.ReactElement;
  export function ChevronRight(props?: LucideProps): React.ReactElement;
  export function Plus(props?: LucideProps): React.ReactElement;
  export function Minus(props?: LucideProps): React.ReactElement;
  export function Dot(props?: LucideProps): React.ReactElement;
  export function CheckCircle(props?: LucideProps): React.ReactElement;
  export function Circle(props?: LucideProps): React.ReactElement;
  export function Square(props?: LucideProps): React.ReactElement;
  export function SquareCheck(props?: LucideProps): React.ReactElement;
  export function SquarePlus(props?: LucideProps): React.ReactElement;
  export function SquareMinus(props?: LucideProps): React.ReactElement;
  export function Equal(props?: LucideProps): React.ReactElement;
  export function NotEqual(props?: LucideProps): React.ReactElement;
  export function GreaterThan(props?: LucideProps): React.ReactElement;
  export function LessThan(props?: LucideProps): React.ReactElement;
  export function Divide(props?: LucideProps): React.ReactElement;
  export function Multiply(props?: LucideProps): React.ReactElement;
  export function Percent(props?: LucideProps): React.ReactElement;
  export function Hash(props?: LucideProps): React.ReactElement;
  export function AtSign(props?: LucideProps): React.ReactElement;
  export function Ampersand(props?: LucideProps): React.ReactElement;
  export function Drop(props?: LucideProps): React.ReactElement;
  export function Droplet(props?: LucideProps): React.ReactElement;
  export function Snowflake(props?: LucideProps): React.ReactElement;
  export function Cloud(props?: LucideProps): React.ReactElement;
  export function CloudRain(props?: LucideProps): React.ReactElement;
  export function CloudLightning(props?: LucideProps): React.ReactElement;
  export function CloudOff(props?: LucideProps): React.ReactElement;
  export function Wind(props?: LucideProps): React.ReactElement;
  export function Thermometer(props?: LucideProps): React.ReactElement;
  export function ThermometerSun(props?: LucideProps): React.ReactElement;
  export function ThermometerSnow(props?: LucideProps): React.ReactElement;
  export function Flame(props?: LucideProps): React.ReactElement;
  export function TreePine(props?: LucideProps): React.ReactElement;
  export function Leaf(props?: LucideProps): React.ReactElement;
  export function Flower2(props?: LucideProps): React.ReactElement;
  export function Sprout(props?: LucideProps): React.ReactElement;
  export function Mushroom(props?: LucideProps): React.ReactElement;
  export function Bug(props?: LucideProps): React.ReactElement;
  export function Ant(props?: LucideProps): React.ReactElement;
  export function Cricket(props?: LucideProps): React.ReactElement;
  export function Bird(props?: LucideProps): React.ReactElement;
  export function Dog(props?: LucideProps): React.ReactElement;
  export function Cat(props?: LucideProps): React.ReactElement;
  export function Fish(props?: LucideProps): React.ReactElement;
  export function Octopus(props?: LucideProps): React.ReactElement;
  export function Shell(props?: LucideProps): React.ReactElement;
  export function Cow(props?: LucideProps): React.ReactElement;
  export function Mouse(props?: LucideProps): React.ReactElement;
  export function Rabbit(props?: LucideProps): React.ReactElement;
  export function Elephant(props?: LucideProps): React.ReactElement;
  export function Lion(props?: LucideProps): React.ReactElement;
  export function Tiger(props?: LucideProps): React.ReactElement;
  export function Wolf(props?: LucideProps): React.ReactElement;
  export function Bear(props?: LucideProps): React.ReactElement;
  export function Fox(props?: LucideProps): React.ReactElement;
  export function Deer(props?: LucideProps): React.ReactElement;
  export function Raccoon(props?: LucideProps): React.ReactElement;
  export function Skunk(props?: LucideProps): React.ReactElement;
  export function Whale(props?: LucideProps): React.ReactElement;
  export function Dolphin(props?: LucideProps): React.ReactElement;
  export function Frog(props?: LucideProps): React.ReactElement;
  export function Turtle(props?: LucideProps): React.ReactElement;
  export function Snake(props?: LucideProps): React.ReactElement;
  export function Lizard(props?: LucideProps): React.ReactElement;
  export function Crocodile(props?: LucideProps): React.ReactElement;
  export function Penguin(props?: LucideProps): React.ReactElement;
  export function Owl(props?: LucideProps): React.ReactElement;
  export function Bat(props?: LucideProps): React.ReactElement;
  export function Raven(props?: LucideProps): React.ReactElement;
  export function Swan(props?: LucideProps): React.ReactElement;
  export function Duck(props?: LucideProps): React.ReactElement;
  export function Goose(props?: LucideProps): React.ReactElement;
  export function Flamingo(props?: LucideProps): React.ReactElement;
  export function Peacock(props?: LucideProps): React.ReactElement;
  export function Parrot(props?: LucideProps): React.ReactElement;
  export function Macaw(props?: LucideProps): React.ReactElement;
  export function Toucan(props?: LucideProps): React.ReactElement;
  export function Hummingbird(props?: LucideProps): React.ReactElement;
  export function Woodpecker(props?: LucideProps): React.ReactElement;
  export function Eagle(props?: LucideProps): React.ReactElement;
  export function Hawk(props?: LucideProps): React.ReactElement;
  export function Falcon(props?: LucideProps): React.ReactElement;
  export function Vulture(props?: LucideProps): React.ReactElement;
  export function Condor(props?: LucideProps): React.ReactElement;
  export function Pelican(props?: LucideProps): React.ReactElement;
  export function Stork(props?: LucideProps): React.ReactElement;
  export function Heron(props?: LucideProps): React.ReactElement;
  export function Crane(props?: LucideProps): React.ReactElement;
  export function Ibis(props?: LucideProps): React.ReactElement;
  export function Spoonbill(props?: LucideProps): React.ReactElement;
  export function MenuLeft(props?: LucideProps): React.ReactElement;
  export function MenuRight(props?: LucideProps): React.ReactElement;
  export function PanelLeftOpen(props?: LucideProps): React.ReactElement;
}
