[options]
admin_passwd = iP@ssw0rd
db_host = postgres
db_port = 5432
db_user = hexastudio
db_password = 1091949815f2db0f0c16ec255c3e5d6a
db_name = hexastudio_odoo
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
proxy_mode = True
list_db = False
workers = 4
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200
max_cron_threads = 2
