apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: false
    jsonData:
      derivedFields:
        - name: traceID
          matcherRegex: "trace_id=(\\w+)"
          url: '${__value.raw}'
          datasourceUid: tempo
          urlDisplayLabel: "View Trace"
      maxLines: 2000
      timeout: "60s"
