/**
 * HEXA STUDIO — Design Tokens
 * The single source of truth for visual luxury primitives.
 * Auto-generated by `npm run gen-tokens` or `scripts/gen-design-md.js`.
 */

export const DESIGN_SYSTEM = {
  name: "HEXA STUDIO",
  version: "1.0.0",
  description: "Supreme Law of Visual Luxury",

  // The 60-30-10 Color Rule
  colors: {
    // 60% - Background/Base (Void)
    void: "#050505",
    // 30% - Main Accent (Obsidian)
    obsidian: "#0F0F10",
    // 10% - Highlight/Gold (Gold)
    gold: "#D4AF37",
  },

  // Editorial Typography
  typography: {
    headingFont: "Bodoni Moda",
    bodyFont: "Inter",
    monoFont: "JetBrains Mono",
    headingTracking: "-0.02em", // default, can be overridden
    bodySize: "1rem",
  },

  // Motion Tokens
  motion: {
    easeDefault: "--hexa-ease-out",
    easeEnter: "--hexa-ease-in",
    easeExit: "--hexa-ease-out",
  },

  // Governance
  luxuryScoreThreshold: 80, // CI/CD Gate threshold
  luxuryScorePerfect: 100,
} as const;

export type DesignSystem = typeof DESIGN_SYSTEM;